# Generated by Django 5.1.1 on 2024-09-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='img',
            new_name='img1',
        ),
    ]
