# Generated by Django 5.1.1 on 2024-09-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_rename_img_poll_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
