# Generated by Django 5.1.1 on 2024-09-22 14:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='dis1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='dis2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
