# Generated by Django 5.1.1 on 2024-09-22 14:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_poll_dis1_alter_poll_dis2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='dis1',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='dis2',
            field=tinymce.models.HTMLField(),
        ),
    ]
