# Generated by Django 5.1.1 on 2024-09-22 14:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_poll_dis1_alter_poll_dis2'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
