# Generated by Django 5.1.1 on 2024-09-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_poll_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='slug',
            new_name='slugs',
        ),
    ]
