# Generated by Django 5.1.1 on 2024-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_rename_slug_poll_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('vote_id', models.IntegerField()),
            ],
        ),
    ]
