# Generated by Django 5.1.1 on 2024-10-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_delete_data_rename_dis1_poll_exterior_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='detailpage_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
