# Generated by Django 5.1.1 on 2024-10-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_poll_detailpage_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='Homepage_img',
            new_name='main_img',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='detailpage_img',
        ),
    ]
