# Generated by Django 5.1.1 on 2024-10-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_rename_homepage_img_poll_main_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('selected_id', models.CharField(max_length=50)),
            ],
        ),
    ]
